### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Marcosreuquen** [Lio-n/dwf-m9-desafio#1]
Buenas tardes, @Lio-n 

**Felicitaciones por tu desafío!!**
Realmente está excelente. El tipado que le diste al proyecto completo es destacable. Cómo organizaste los módulos y la centralización de exports que le diste a las carpetas es impecable. :clap: Me gustó mucho! 

Estaría bueno agregarle los schemas del address en la doc de postman.

Felictaciones y éxitos en el siguiente módulo!! :partying_face: 
Saludos!

**Comment by Lio-n** [comment]
Buenas, @Marcosreuquen
Muchas Gracias!
